name: Deploy API Gateway Config

on:
  push:
    branches:
      - main
    paths:
      - 'kong.yml'
      - 'docker-compose.yml'

jobs:
  trigger-coolify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Coolify Deployment
        run: |
          curl -X POST "${{ secrets.COOLIFY_URL_WH }}" -H "Authorization: Bearer ${{ secrets.COOLIFY_API_KEY }}"